// using extension "REST Client" in VSCode
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFudWVsIiwiaWF0IjoxNjc1NjA1Mzg0LCJleHAiOjE2NzU2MDUzOTl9.iV3T9YXPO-HXr6jJX9yxby0dIffKuzijY9TuaRjdq54

// ### <- starts new request
### 

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFudWVsIiwiaWF0IjoxNjc1NjA1MzYxfQ.1xR7im8xi8rSikL7onfxf_0KFg2KKrCKdxZUSkjPmaA"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWFudWVsIiwiaWF0IjoxNjc1NjA1MzYxfQ.1xR7im8xi8rSikL7onfxf_0KFg2KKrCKdxZUSkjPmaA"}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Manuel"
}